### ISSUE TITLE
Extending requests

### ISSUE THREAD

**Issue by RReverser** [sapphi-red/swagger-ui-plugin-enum-names#1]
Thanks for the plugin!

Unfortunately, it seems it only extends the response schema view at the moment, e.g. here:

![image](https://user-images.githubusercontent.com/557590/195232078-be83a8d3-f39a-4bdc-83c3-631e7b94b57b.png)

enums work well, but when similarly annotated enums are used in query parameters:

![image](https://user-images.githubusercontent.com/557590/195232193-9ee6b124-bf04-4318-b701-134cb70852c8.png)

or request bodies:

![image](https://user-images.githubusercontent.com/557590/195232268-c2968b21-f9bb-45a2-b051-0738dbefb13a.png)

then those remain plain numbers and don't have the names and descriptions attached in any way.

Would it be possible to integrate enum names into those places too?

**Comment by sapphi-red** [comment]
I felt it difficult to change the `<select>` to include names and descriptions without increasing maintenance burden.
So I added a simple info section above the `<select>` (b9e37f11be5c6e4f9560b0241d195ced0c68f485).
![image](https://user-images.githubusercontent.com/49056869/195824213-cb1bab90-eaeb-4b93-a790-34b45e9e783b.png)
