### ISSUE TITLE
Error thrown when Enum is used as parameter.

### ISSUE THREAD

**Issue by DamienLaw** [sapphi-red/swagger-ui-plugin-enum-names#2]
While this plugin displays schema as expected,
![image](https://user-images.githubusercontent.com/14930009/196333097-e8bf99fc-f86e-4af3-9538-b9f1b9729022.png)

it's not displaying an API's parameters if one of those parameters is an enum.
![image](https://user-images.githubusercontent.com/14930009/196331695-e0bc8f6f-bbf5-4122-a41a-dfceaa7b423c.png)

And it's throwing errors in developer tools console.

![image](https://user-images.githubusercontent.com/14930009/196332088-6a2e7ee0-ff9b-41b7-a68b-58e93987194a.png)

The screenshot below is the API without the plugin, I'm expecting that with the help of the plugin, the dropdown would list the enum's name instead of the values.
![image](https://user-images.githubusercontent.com/14930009/196332802-16ea2faa-3be0-4331-b800-90adfd4d680f.png)

**Comment by sapphi-red** [comment]
@DamienLaw Would you provide a spec json/yaml that reproduces the error?

Does it happen from 4.1.0? I guess it doesn't happen with 4.0.1.

**Comment by DamienLaw** [comment]
I'm using `swagger-ui-dist@4.13.2` and `swagger-ui-plugin-enum-names@4.0.1`.
Even the latest version `4.14.3` and `4.1.0` respectively have this issue.

You can refer to the swagger UI at
https://bankbot.bytedash.my/swagger

A sample of the yaml can be found here
https://bankbot.bytedash.my/swagger/v1/swagger.yaml

Take a look at the `GetAll` apis of `BankAccount`, `BankTransaction` or `BankLog`

**Comment by sapphi-red** [comment]
@DamienLaw I've released 4.1.1 and the error should be fixed.

**Comment by DamienLaw** [comment]
That was fast. Thanks a lot.

I've tested it and it's working fine. There's a suggestion on multi-selectable enums that I would like to put forth.
I'll open a new issue for that.
